chore: add phisherman plugin
sapphiredev/plugins pull request #215
Opened 2022-01-09 09:33 UTC by UndiedGamer

2022-01-10 21:17 UTC, favna requested changes

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/tsconfig.json
> +		"preserveConstEnums": true,
```suggestion
```

2022-01-10 21:17 UTC, favna commented on packages/phisherman/tsconfig.json
> +		"preserveConstEnums": true,
```suggestion
```

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/index.ts
> +import type { Phisherman, PhishermanOptions } from '.';
```suggestion
import type { Phisherman, PhishermanOptions } from './lib/Phisherman';
```

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/register.ts
> +import { Phisherman } from '.';
```suggestion
import { Phisherman } from './lib/Phisherman';
import './index';
```

The bottom part to ensure that calling `/register` also includes the module augmentations.

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/lib/Phisherman.ts
> +	public options;
```suggestion
	public options: PhishermanOptions;
```

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/lib/Phisherman.ts
> +import fetch, { Headers } from 'node-fetch';
How do you manage to add a dependency on @sapphire/fetch but not use @sapphire/fetch lol

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/lib/Phisherman.ts
> +		});
Don't use promises in constructor. That doesn't really work. Instead dedicate this to a method called `init`

2022-01-10 21:17 UTC, favna commented on packages/phisherman/src/lib/Phisherman.ts
> +			return check as Promise<PhishermanReturnType>;
```suggestion
			return await fetch<PhishermanReturnType>(`https://api.phisherman.gg/v2/domains/check/${domain}`, {
				headers: {
					'Content-Type': 'application/json',
					Authorization: `Bearer ${this.options?.apiKey}`
				}
			}, FetchResultTypes.JSON);
```

After changing fetch to @sapphire/fetch

2022-01-10 21:29 UTC, noftaly requested changes

2022-01-10 21:29 UTC, noftaly commented on packages/phisherman/package.json
> +	"homepage": "https://github.com/sapphiredev/plugins/tree/main/packages/editable-commands",
```suggestion
	"homepage": "https://github.com/sapphiredev/plugins/tree/main/packages/phisherman",
```

2022-01-10 21:34 UTC, noftaly commented on packages/phisherman/README.md
> +With plugin-phisherman, you can have out of box integration with [Phisherman](https://phisherman.gg).
Maybe also add a line or two on what Phisherman is?

2022-01-10 22:09 UTC, favna requested changes
Other than the one comment from @noftaly above there's the following to address

- In the description add what phisherman is. I would add this but their site is down at time of writing.
- This should not be a plugin but rather can be moved to the utilities monorepo and be published as `@sapphire/phisherman`. I did some of the heavy lifting for you already by preparing most of the code, you just need to move it and create the PR, then update 
  - `CODEOWNERS`
  - `.npm-deprecaterc.yml`
  - root README (add the badge)
  - Validate the code builds, as I cannot test that until it's in that repo.

2022-01-11 01:48 UTC, UndiedGamer commented on packages/phisherman/src/lib/Phisherman.ts
> +		return result.value!.message === 'missing permissions or invalid API key';
They don't give an error code, if they're not authorised it returns
```json
{
"success" : false,
"message": "whatever I was checking there"
}
```

2022-01-11 03:34 UTC, closed without merging