feat(api): Add automatically connect option
sapphiredev/plugins pull request #250
Opened 2022-03-02 02:04 UTC by jczstudios

If set to false, the API server will not automatically call connect. This can used to change options after construction of the client or only connect on some instances when sharded.

2022-03-02 17:36 UTC, favna requested changes
This will work better

https://user-images.githubusercontent.com/4019718/156416939-2b1da1cf-5a97-48a5-8954-1a3161e74b4a.mp4

2022-03-02 17:36 UTC, favna commented on packages/api/src/register.ts
> +		}
```suggestion
		if (!(server.options.automaticallyConnect ?? true)) {
			return;
		}
```

2022-03-02 17:36 UTC, favna commented on packages/api/src/lib/structures/http/Server.ts
> +	 * Should the server automatically connect when the plugin is loaded.
```suggestion
	 * Whether the server should connect upon being when the plugin is loaded.
```

2022-03-02 17:36 UTC, favna commented on packages/api/src/lib/structures/http/Server.ts
> +	 * @since 3.1.4
```suggestion
	 * @since 3.2.0
```

2022-03-02 17:56 UTC, jczstudios commented
Yeah, that's better. Thanks.

2022-03-02 19:35 UTC, favna approved these changes

2022-03-02 20:04 UTC, favna commented
@sapphiredev pack

2022-03-05 10:32 UTC, kyranet approved these changes

2022-03-05 11:38 UTC, merged