perf(i18next): switch to new backend library
sapphiredev/plugins pull request #285
Opened 2022-05-05 21:13 UTC by favna

Goodbye library written in the year 0, hello library written in 2022.

2022-05-05 21:15 UTC, vladfrangu submitted a review, later dismissed

2022-05-05 21:16 UTC, favna commented
@sapphiredev pack

2022-05-06 19:46 UTC, vladfrangu submitted a review, later dismissed

2022-05-07 10:01 UTC, kyranet submitted a review, later dismissed

2022-05-07 10:22 UTC, Nytelife26 commented
I'm gonna request a hold on this until I can review it later today if that's okay. Thanks in advance

2022-05-07 19:23 UTC, imranbarbhuiya requested changes

2022-05-07 19:23 UTC, imranbarbhuiya commented on package.json
>  		"ts-node": "^10.7.0",
Ig you can remove ts-node now.

2022-05-07 19:24 UTC, favna commented on package.json
>  		"ts-node": "^10.7.0",
good catch

2022-05-07 19:27 UTC, imranbarbhuiya commented
I missed you can remove the resolutions too.

2022-05-07 20:06 UTC, merged