feat(plugin-i18next): localized builders
sapphiredev/plugins pull request #372
Opened 2022-10-13 19:35 UTC by Arcadia148

This PR ports applyLocalizedBuilder and createSelectMenuChoiceName from @skyra/http-framework-i18n

I did also consider having a resolveLocale function which would convert locales like "ja-JP" to ones assignable to type LocaleString. (https://github.com/Arcadia148/plugins/blob/feat/localizedBuilders2/packages/i18next/src/lib/functions.ts#L189)

This PR closes #353

2022-10-15 11:04 UTC, favna reviewed
<snip> I'm dumb

2022-10-15 11:10 UTC, favna commented
The issue #373 has been created and #353 has been adjusted to only mention the one function

2022-10-15 11:12 UTC, favna submitted a review, later dismissed

2022-10-15 11:15 UTC, vladfrangu requested changes

2022-10-15 11:15 UTC, vladfrangu commented on packages/i18next/src/lib/functions.ts
> +function isSupportedDiscordLocale(language: string): language is LocaleString {
```suggestion
const supportedLanguages = new Set(Object.values(Locale)) as ReadonlySet<LocaleString>;

function isSupportedDiscordLocale(language: string): language is LocaleString {
```

2022-10-15 11:15 UTC, vladfrangu commented on packages/i18next/src/lib/functions.ts
> +				detail: `'${locale}' is not assignable to type LocaleString`
Maybe make the message more of a `'${locale}' needs to be one of: ${locales}`

2022-10-15 11:15 UTC, vladfrangu commented on packages/i18next/src/lib/functions.ts
> +		throw new TypeError(`Unsupported Discord locale\n'${defaultLocale}' is not assignable to type LocaleString`);
Ditto

2022-10-15 11:50 UTC, favna commented on packages/i18next/src/lib/functions.ts
> +		throw new TypeError(`Unsupported Discord locale\n'${defaultLocale}' is not assignable to type LocaleString`);
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/4019718/195984877-df9f5aa4-f869-4329-b08a-bf6c8b2e667c.png">

2022-10-15 12:05 UTC, favna approved these changes

2022-10-15 14:48 UTC, vladfrangu approved these changes

2022-10-16 09:41 UTC, Swiizyy commented
@sapphiredev pack

2022-10-16 10:11 UTC, merged