feat: add utilities-store plugin
sapphiredev/plugins pull request #415
Opened 2023-01-29 17:15 UTC by favna

ref: https://discord.com/channels/737141877803057244/1065277250515238952
ref: https://discord.com/channels/737141877803057244/737142940777971773/1068427455523737611

2023-01-29 17:30 UTC, c43721 requested changes

2023-01-29 17:30 UTC, c43721 commented on .github/CODEOWNERS
> +/packages/subcommands/**/*.ts @fanva @vladfrangu
fyi `fanva` is spelt wrong here :)

2023-02-04 14:52 UTC, vladfrangu requested changes
I also don't really understand why we don't just let users make a class that exports multiple methods and they're all accessible. This doesn't really...feel nice.

Also was reloading the piece even tested? I don't see any code to handle the re-exposing of the utility method.

2023-02-04 14:52 UTC, vladfrangu commented on packages/utilities-store/src/lib/Utilities.ts
> +		this[name] = func.handle;
This will make it lose the `this` context. Image a utility class that goes
```ts
this.container.logger.warn();
```

Yeah, that won't be happy

2023-02-17 13:51 UTC, vladfrangu submitted a review, later dismissed

2023-02-17 22:07 UTC, merged